Updating variable declaration in collector-config-amp.yaml
When applying collector-config-amp.yaml, all variables in the yaml need to have double $ signs ($$var). However, one line managed to sneak in, causing parsing errors in the collector pods:
```
Error: failed to resolve config: cannot resolve the configuration: cannot convert the confmap.Conf: environment variable "1" has invalid name: must match regex ^[a-zA-Z_][a-zA-Z0-9_]*$
2025/02/04 18:38:44 application run finished with error: failed to resolve config: cannot resolve the configuration: cannot convert the confmap.Conf: environment variable "1" has invalid name: must match regex ^[a-zA-Z_][a-zA-Z0-9_]*$
```